### ISSUE TITLE
Binaries in doozer-0.7-darwin-amd64.tar.gz not executable

### ISSUE THREAD

**Issue by danp** [ha/doozerd#3]
`doozer` and `doozerd` in the doozer-0.7-darwin-amd64.tar.gz archive are not executable.

**Comment by bmizerany** [comment]
Fixed.

**Comment by danp** [comment]
Looks like this is still an issue in `doozerd-0.8-darwin-amd64.tar.gz`. Was `dist.sh` used to build it?
